using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Generator.Writer
{
    public abstract class Writer
    {
        public abstract void Interface();

        public abstract void DatabaseContext();

        public abstract void DatabaseContextFactory();

        public abstract void FakeContextFactory();

        public abstract void PocoClasses();

        public abstract void PocoConfiguration();

        public abstract void StoredProcedureReturnModels();

        private readonly GeneratedTextTransformation _outer;

        private readonly Dictionary<string, bool> _supportedFrameworkVersionCache;

        private readonly Version _version;

        private readonly string _codeGeneratedAttribute;

        protected readonly StringBuilder _preHeaderInfo;

        protected readonly StringBuilder _headerInfo;

        protected Writer(GeneratedTextTransformation outer)
        {
            _outer = outer;
            _supportedFrameworkVersionCache = new Dictionary<string, bool>();
            _version = new Version(3, 0, 0);
            _codeGeneratedAttribute = string.Format("[System.CodeDom.Compiler.GeneratedCode(\"EF.Reverse.POCO.Generator\", \"{0}\")]", _version);

            // Build header info
            _preHeaderInfo = new StringBuilder();
            _preHeaderInfo.AppendLine("// ------------------------------------------------------------------------------------------------");
            _preHeaderInfo.AppendLine("// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).");
            _preHeaderInfo.AppendLine("// Created by Simon Hughes (https://about.me/simon.hughes).");
            _preHeaderInfo.AppendLine("//");
            _preHeaderInfo.AppendLine("// Do not make changes directly to this file - edit the template instead.");

            if (Settings.IncludeConnectionSettingComments)
            {
                _preHeaderInfo.AppendLine("//");
                _preHeaderInfo.AppendLine("// The following connection settings were used to generate this file:");
                if (!string.IsNullOrEmpty(Settings.ConnectionStringName) && !string.IsNullOrEmpty(Settings.ConfigFilePath))
                {
                    _preHeaderInfo.AppendLine(string.Format("//     Configuration file:     \"{0}\"", Settings.ConfigFilePath));
                    _preHeaderInfo.AppendLine(string.Format("//     Connection String Name: \"{0}\"", Settings.ConnectionStringName));
                }
                _preHeaderInfo.AppendLine(string.Format("//     Connection String:      \"{0}\"", ZapPassword()));
            }
            _preHeaderInfo.AppendLine("// ------------------------------------------------------------------------------------------------");

            _headerInfo = new StringBuilder();
            _headerInfo.AppendLine("// <auto-generated>");
            _headerInfo.AppendLine("// ReSharper disable ConvertPropertyToExpressionBody");
            _headerInfo.AppendLine("// ReSharper disable DoNotCallOverridableMethodsInConstructor");
            _headerInfo.AppendLine("// ReSharper disable EmptyNamespace");
            _headerInfo.AppendLine("// ReSharper disable InconsistentNaming");
            _headerInfo.AppendLine("// ReSharper disable PartialMethodWithSinglePart");
            _headerInfo.AppendLine("// ReSharper disable PartialTypeWithSinglePart");
            _headerInfo.AppendLine("// ReSharper disable RedundantNameQualifier");
            _headerInfo.AppendLine("// ReSharper disable RedundantOverridenMember");
            _headerInfo.AppendLine("// ReSharper disable UseNameofExpression");
            _headerInfo.AppendLine("// TargetFrameworkVersion = " + Settings.TargetFrameworkVersion);
            _headerInfo.AppendLine("#pragma warning disable 1591    //  Ignore \"Missing XML Comment\" warning");
            _headerInfo.AppendLine();
        }

        public virtual void Init()
        {
        }

        private string ZapPassword()
        {
            var rx = new Regex("password=[^\";]*", RegexOptions.Singleline | RegexOptions.Multiline | RegexOptions.IgnoreCase);
            return rx.Replace(Settings.ConnectionString, "password=**zapped**;");
        }

        public void Test()
        {
            Header();

            if (Settings.ElementsToGenerate.HasFlag(Elements.Interface) && !string.IsNullOrWhiteSpace(Settings.DbContextInterfaceName))
                Interface();

            DatabaseContext();
            DatabaseContextFactory();
            FakeContextFactory();
            PocoClasses();
            PocoConfiguration();
            StoredProcedureReturnModels();

            Footer();
        }

        public void AppendPreHeaderInfo(string databaseDetails)
        {
            _preHeaderInfo.Append(databaseDetails);
        }

        public void PreHeaderInfo()
        {
            _outer.WriteLine(_preHeaderInfo.ToString());
        }

        public virtual void Header()
        {
            PreHeaderInfo();
            _outer.WriteLine(_headerInfo.ToString());
        }

        public virtual void Footer()
        {
            _outer.WriteLine("}");
            _outer.WriteLine("// </auto-generated>");
        }

        public void ConnectionSettingComments()
        {

        }

        public bool IsSupportedFrameworkVersion(string frameworkVersion)
        {
            if (_supportedFrameworkVersionCache.ContainsKey(frameworkVersion))
                return _supportedFrameworkVersionCache[frameworkVersion];

            var nfi = CultureInfo.InvariantCulture.NumberFormat;
            var isSupported = float.Parse(frameworkVersion, nfi);
            var result = isSupported <= Settings.TargetFrameworkVersion;
            _supportedFrameworkVersionCache.Add(frameworkVersion, result);
            return result;
        }

        #region Callbacks

        // Callbacks **********************************************************************************************************************
        // This method will be called right before we write the POCO header.
        public void PocoClassAttributes(Table t)
        {
            if (Settings.UseDataAnnotations)
            {
                foreach (var dataAnnotation in t.DataAnnotations)
                {
                    _outer.WriteLine("    [" + dataAnnotation + "]");
                }
            }

            // Example:
            // if(t.ClassName.StartsWith("Order"))
            //     WriteLine("    [SomeAttribute]");
        }

        // This method will be called right before we write the POCO header.
        public void PocoClassExtendedComments(Table t)
        {
            if (Settings.IncludeExtendedPropertyComments != CommentsStyle.None && t.ExtendedProperty.Any())
            {
                var lines = t.ExtendedProperty
                    .SelectMany(x => x.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries))
                    .ToList();

                _outer.WriteLine("    ///<summary>");
                foreach (var line in lines)
                {
                    _outer.WriteLine("    /// {0}", System.Security.SecurityElement.Escape(line));
                }
                _outer.WriteLine("    ///</summary>");
            }
        }

        // Writes optional base classes
        public string PocoBaseClasses(Table t)
        {
            //if (t.ClassName == "User")
            //    return ": IdentityUser<int, CustomUserLogin, CustomUserRole, CustomUserClaim>";

            // Or use the maker class to dynamically build more complex definitions
            /* Example:
            var r = new BaseClassMaker("POCO.Sample.Data.MetaModelObject");
            r.AddInterface("POCO.Sample.Data.IObjectWithTableName");
            r.AddInterface("POCO.Sample.Data.IObjectWithId",
                t.Columns.Any(x => x.IsPrimaryKey && !x.IsNullable && x.NameHumanCase.Equals("Id", StringComparison.InvariantCultureIgnoreCase) && x.PropertyType == "long"));
            r.AddInterface("POCO.Sample.Data.IObjectWithUserId",
                t.Columns.Any(x => !x.IsPrimaryKey && !x.IsNullable && x.NameHumanCase.Equals("UserId", StringComparison.InvariantCultureIgnoreCase) && x.PropertyType == "long"));
            return r.ToString();
            */

            return "";
        }

        // Writes any boilerplate stuff inside the POCO class
        public void PocoBaseClassBody(Table t)
        {
            // Do nothing by default
            // Example:
            // WriteLine("        // " + t.ClassName);
        }

        public string PocoColumn(Column c)
        {
            var commentWritten = false;
            if ((Settings.IncludeExtendedPropertyComments == CommentsStyle.InSummaryBlock ||
                 Settings.IncludeComments == CommentsStyle.InSummaryBlock) &&
                !string.IsNullOrEmpty(c.SummaryComments))
            {
                _outer.WriteLine(string.Empty);
                _outer.WriteLine("        ///<summary>");
                _outer.WriteLine("        /// {0}", System.Security.SecurityElement.Escape(c.SummaryComments));
                _outer.WriteLine("        ///</summary>");
                commentWritten = true;
            }
            if (Settings.UseDataAnnotations)
            {
                if (c.Ordinal > 1 && !commentWritten)
                    _outer.WriteLine(string.Empty);    // Leave a blank line before the next property

                foreach (var dataAnnotation in c.DataAnnotations)
                {
                    _outer.WriteLine("        [" + dataAnnotation + "]");
                }
            }

            // Example of adding a [Required] data annotation attribute to all non-null fields
            //if (!c.IsNullable)
            //    return "        [System.ComponentModel.DataAnnotations.Required] " + c.Entity;

            return "        " + c.Entity;
        }

        #endregion
    }
}