using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace Generator.Writer
{
    public abstract class Writer
    {
        public abstract void Init();
        protected abstract void StoredProcedureReturnModels();
        protected abstract void PocoConfiguration();
        protected abstract void PocoClasses();
        protected abstract void FakeContextFactory();
        protected abstract void DatabaseContextFactory();
        protected abstract void DatabaseContext();
        protected abstract void Interface();

        private readonly GeneratedTextTransformation _outer;
        private readonly Dictionary<string, bool> _supportedFrameworkVersionCache;
        private readonly Version _version;
        private readonly string _codeGeneratedAttribute;

        protected Writer(GeneratedTextTransformation outer)
        {
            _outer = outer;
            _supportedFrameworkVersionCache = new Dictionary<string, bool>();
            _version = new Version(3, 0, 0);
            _codeGeneratedAttribute = string.Format("[System.CodeDom.Compiler.GeneratedCode(\"EF.Reverse.POCO.Generator\", \"{0}\")]", _version);
        }

        public void Write()
        {
            StartHeader();

            if (Settings.ElementsToGenerate.HasFlag(Elements.Interface) && !string.IsNullOrWhiteSpace(Settings.DbContextInterfaceName))
                Interface();

            DatabaseContext();
            DatabaseContextFactory();
            FakeContextFactory();
            PocoClasses();
            PocoConfiguration();
            StoredProcedureReturnModels();
        }

        protected virtual void StartHeader()
        {
            _outer.WriteLine("// <auto-generated>");
            _outer.WriteLine("// ReSharper disable ConvertPropertyToExpressionBody");
            _outer.WriteLine("// ReSharper disable DoNotCallOverridableMethodsInConstructor");
            _outer.WriteLine("// ReSharper disable EmptyNamespace");
            _outer.WriteLine("// ReSharper disable InconsistentNaming");
            _outer.WriteLine("// ReSharper disable PartialMethodWithSinglePart");
            _outer.WriteLine("// ReSharper disable PartialTypeWithSinglePart");
            _outer.WriteLine("// ReSharper disable RedundantNameQualifier");
            _outer.WriteLine("// ReSharper disable RedundantOverridenMember");
            _outer.WriteLine("// ReSharper disable UseNameofExpression");
            _outer.WriteLine("// TargetFrameworkVersion = {0}", Settings.TargetFrameworkVersion);
            _outer.WriteLine("#pragma warning disable 1591    //  Ignore \"Missing XML Comment\" warning");
        }

        protected virtual void StartFooter()
        {
            _outer.WriteLine("}");
            _outer.WriteLine("// </auto-generated>");
        }

        protected void ConnectionSettingComments()
        {

        }

        public bool IsSupportedFrameworkVersion(string frameworkVersion)
        {
            if (_supportedFrameworkVersionCache.ContainsKey(frameworkVersion))
                return _supportedFrameworkVersionCache[frameworkVersion];

            var nfi = CultureInfo.InvariantCulture.NumberFormat;
            var isSupported = float.Parse(frameworkVersion, nfi);
            var result = isSupported <= Settings.TargetFrameworkVersion;
            _supportedFrameworkVersionCache.Add(frameworkVersion, result);
            return result;
        }

        #region Callbacks

        // Callbacks **********************************************************************************************************************
        // This method will be called right before we write the POCO header.
        public void PocoClassAttributes(Table t)
        {
            if (Settings.UseDataAnnotations)
            {
                foreach (var dataAnnotation in t.DataAnnotations)
                {
                    _outer.WriteLine("    [" + dataAnnotation + "]");
                }
            }

            // Example:
            // if(t.ClassName.StartsWith("Order"))
            //     WriteLine("    [SomeAttribute]");
        }

        // This method will be called right before we write the POCO header.
        public void PocoClassExtendedComments(Table t)
        {
            if (Settings.IncludeExtendedPropertyComments != CommentsStyle.None && t.ExtendedProperty.Any())
            {
                var lines = t.ExtendedProperty
                    .SelectMany(x => x.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries))
                    .ToList();

                _outer.WriteLine("    ///<summary>");
                foreach (var line in lines)
                {
                    _outer.WriteLine("    /// {0}", System.Security.SecurityElement.Escape(line));
                }
                _outer.WriteLine("    ///</summary>");
            }
        }

        // Writes optional base classes
        public string PocoBaseClasses(Table t)
        {
            //if (t.ClassName == "User")
            //    return ": IdentityUser<int, CustomUserLogin, CustomUserRole, CustomUserClaim>";

            // Or use the maker class to dynamically build more complex definitions
            /* Example:
            var r = new BaseClassMaker("POCO.Sample.Data.MetaModelObject");
            r.AddInterface("POCO.Sample.Data.IObjectWithTableName");
            r.AddInterface("POCO.Sample.Data.IObjectWithId",
                t.Columns.Any(x => x.IsPrimaryKey && !x.IsNullable && x.NameHumanCase.Equals("Id", StringComparison.InvariantCultureIgnoreCase) && x.PropertyType == "long"));
            r.AddInterface("POCO.Sample.Data.IObjectWithUserId",
                t.Columns.Any(x => !x.IsPrimaryKey && !x.IsNullable && x.NameHumanCase.Equals("UserId", StringComparison.InvariantCultureIgnoreCase) && x.PropertyType == "long"));
            return r.ToString();
            */

            return "";
        }

        // Writes any boilerplate stuff inside the POCO class
        public void PocoBaseClassBody(Table t)
        {
            // Do nothing by default
            // Example:
            // WriteLine("        // " + t.ClassName);
        }

        public string PocoColumn(Column c)
        {
            var commentWritten = false;
            if ((Settings.IncludeExtendedPropertyComments == CommentsStyle.InSummaryBlock ||
                 Settings.IncludeComments == CommentsStyle.InSummaryBlock) &&
                !string.IsNullOrEmpty(c.SummaryComments))
            {
                _outer.WriteLine(string.Empty);
                _outer.WriteLine("        ///<summary>");
                _outer.WriteLine("        /// {0}", System.Security.SecurityElement.Escape(c.SummaryComments));
                _outer.WriteLine("        ///</summary>");
                commentWritten = true;
            }
            if (Settings.UseDataAnnotations)
            {
                if (c.Ordinal > 1 && !commentWritten)
                    _outer.WriteLine(string.Empty);    // Leave a blank line before the next property

                foreach (var dataAnnotation in c.DataAnnotations)
                {
                    _outer.WriteLine("        [" + dataAnnotation + "]");
                }
            }

            // Example of adding a [Required] data annotation attribute to all non-null fields
            //if (!c.IsNullable)
            //    return "        [System.ComponentModel.DataAnnotations.Required] " + c.Entity;

            return "        " + c.Entity;
        }

        #endregion
    }
}